// <auto-generated />
using System;
using DBContextFile;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mini_ProjectBackend.Migrations
{
    [DbContext(typeof(SecurityDataContext))]
    partial class SecurityDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Mini_Project.Model.Quote", b =>
                {
                    b.Property<int>("QuoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuoteType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QuotesAmt")
                        .HasColumnType("float");

                    b.Property<int>("SecurityID")
                        .HasColumnType("int");

                    b.HasKey("QuoteID");

                    b.ToTable("Quote");
                });

            modelBuilder.Entity("Mini_Project.Model.Security", b =>
                {
                    b.Property<int>("SecurityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AssetClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SecurityID");

                    b.ToTable("Security");
                });
#pragma warning restore 612, 618
        }
    }
}
